### ISSUE TITLE
How do I specify client options?

### ISSUE THREAD

**Issue by yooakim** [microsoft/azuredatastudio-mysql#91]
I am trying to use this driver to connect to ClickHouse using MySql protocol. 

To do that I need to add client option

```
allowPublicKeyRetrieval=true
```

How can I add client optiosn for the MySql driver?

**Comment by rishky-msft** [comment]
Currently the options that user can provide are SQL Modes and Capability Flags.
I am looking for similar options as allowPublicKeyRetrieval.

@yooakim Can you provide me few details that can help me.
1. Is the connection failing without this option? If yes can you add the error message logs?
2. What is the platform? (Mac, Windows or LInux)
3. Do you have any test connection details that can help me replicate the issue?

**Comment by yooakim** [comment]
If you want to you launch a Clickhouse instance with this `docker-compose.yml` @rishky-msft 

```
version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 8123:8123 # Listenoing for HTTP
      - 9000:9000 # Listening for native protocol (tcp)
      - 9004:9004 # Listening for MySQL compatibility protocol
      - 9005:9005 # Listening for PostgreSQL compatibility protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    restart: unless-stopped
    ulimits:
      nofile: 262144
volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local

```
Star the server using docker compose command line:

```
docker compose up -d
```

Then you can try to connect to `localhost` on port 9004 for with a MySQL client. 

I am able to connect with JetBrains DataGrid and their MySql driver but not with Azure Data Studio and MySql driver.

If you simply want to connect to the ClickHouse web UI you can open the page `http://localhost:8123/play` which will let you run (single) commands directly
